#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Juego")]
	public partial class AccesoDatosLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public AccesoDatosLINQDataContext() : 
				base(global::Backend.Properties.Settings.Default.JuegoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarJugador")]
		public int InsertarJugador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="NVarChar(50)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="NVarChar(64)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, contraseña);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearSesion")]
		public int CrearSesion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JugadorID", DbType="Int")] System.Nullable<int> jugadorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sesion", DbType="VarChar(50)")] string sesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jugadorID, sesion, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CambiarEstadoSesion")]
		public int CambiarEstadoSesion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sesion", DbType="VarChar(50)")] string sesion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sesion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerPartidasPorJugador")]
		public ISingleResult<ObtenerPartidasPorJugadorResult> ObtenerPartidasPorJugador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> jugadorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jugadorID);
			return ((ISingleResult<ObtenerPartidasPorJugadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerTodasLasPartidas")]
		public ISingleResult<ObtenerTodasLasPartidasResult> ObtenerTodasLasPartidas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerTodasLasPartidasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RegistrarPartida")]
		public int RegistrarPartida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JugadorID", DbType="Int")] System.Nullable<int> jugadorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Puntuacion", DbType="Int")] System.Nullable<int> puntuacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jugadorID, puntuacion);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class ObtenerPartidasPorJugadorResult
	{
		
		private int _ID;
		
		private System.Nullable<int> _JugadorID;
		
		private System.Nullable<System.DateTime> _FechaHora;
		
		private System.Nullable<int> _Puntuacion;
		
		public ObtenerPartidasPorJugadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JugadorID", DbType="Int")]
		public System.Nullable<int> JugadorID
		{
			get
			{
				return this._JugadorID;
			}
			set
			{
				if ((this._JugadorID != value))
				{
					this._JugadorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHora
		{
			get
			{
				return this._FechaHora;
			}
			set
			{
				if ((this._FechaHora != value))
				{
					this._FechaHora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puntuacion", DbType="Int")]
		public System.Nullable<int> Puntuacion
		{
			get
			{
				return this._Puntuacion;
			}
			set
			{
				if ((this._Puntuacion != value))
				{
					this._Puntuacion = value;
				}
			}
		}
	}
	
	public partial class ObtenerTodasLasPartidasResult
	{
		
		private int _ID;
		
		private System.Nullable<int> _JugadorID;
		
		private System.Nullable<System.DateTime> _FechaHora;
		
		private System.Nullable<int> _Puntuacion;
		
		public ObtenerTodasLasPartidasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JugadorID", DbType="Int")]
		public System.Nullable<int> JugadorID
		{
			get
			{
				return this._JugadorID;
			}
			set
			{
				if ((this._JugadorID != value))
				{
					this._JugadorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHora
		{
			get
			{
				return this._FechaHora;
			}
			set
			{
				if ((this._FechaHora != value))
				{
					this._FechaHora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puntuacion", DbType="Int")]
		public System.Nullable<int> Puntuacion
		{
			get
			{
				return this._Puntuacion;
			}
			set
			{
				if ((this._Puntuacion != value))
				{
					this._Puntuacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
