<?xml version="1.0" encoding="utf-8"?><Database Name="Juego" Class="AccesoDatosLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=proyect--server.database.windows.net;Initial Catalog=Juego;User ID=CloudSA30c43bec" SettingsObjectName="Backend.Properties.Settings" SettingsPropertyName="JuegoConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.InsertarJugador" Method="InsertarJugador">
    <Parameter Name="NombreUsuario" Parameter="nombreUsuario" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Contraseña" Parameter="contraseña" Type="System.String" DbType="NVarChar(64)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CrearSesion" Method="CrearSesion">
    <Parameter Name="JugadorID" Parameter="jugadorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Sesion" Parameter="sesion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CambiarEstadoSesion" Method="CambiarEstadoSesion">
    <Parameter Name="Sesion" Parameter="sesion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>